let listaPalavras = [
    { palavra: "telefone", dica: "Dispositivo para comunicação auditiva à distância" },
    { palavra: "cachorro", dica: "Animal doméstico de estimação com quatro patas" },
    { palavra: "janela", dica: "Abertura em uma parede para entrada de luz" },
    { palavra: "piano", dica: "Instrumento musical de cordas e teclas" },
    { palavra: "macaco", dica: "Animal com cauda que vive em árvores" },
    { palavra: "cadeira", dica: "Móvel para sentar-se" },
    { palavra: "livro", dica: "Objeto com páginas e informações escritas" },
    { palavra: "bicicleta", dica: "Veículo com pedais e duas rodas" },
    { palavra: "mesa", dica: "Superfície plana apoiada por pernas" },
    { palavra: "computador", dica: "Máquina eletrônica para processamento de dados" },
    { palavra: "escola", dica: "Instituição de ensino" },
    { palavra: "lua", dica: "Corpo celeste natural que orbita a Terra" },
    { palavra: "óculos", dica: "Dispositivo usado para melhorar a visão" },
    { palavra: "camisa", dica: "Vestuário para a parte superior do corpo" },
    { palavra: "avião", dica: "Meio de transporte que voa no ar" },
    { palavra: "fruta", dica: "Alimento naturalmente doce ou ácido" },
    { palavra: "arvore", dica: "Planta com tronco e folhas" },
    { palavra: "sapato", dica: "Calçado para proteger os pés" },
    { palavra: "carro", dica: "Meio de transporte terrestre com motor" },
    { palavra: "gato", dica: "Animal doméstico conhecido por sua agilidade" },
    { palavra: "chave", dica: "Instrumento para abrir fechaduras" },
    { palavra: "cinema", dica: "Local para exibição de filmes" },
    { palavra: "relógio", dica: "Instrumento para medir o tempo" },
    { palavra: "sol", dica: "Estrela central do sistema solar" },
    { palavra: "porta", dica: "Barreira móvel que controla o acesso a um espaço" },
    { palavra: "mar", dica: "Grande massa de água salgada" },
    { palavra: "piscina", dica: "Estrutura artificial para nadar" },
    { palavra: "lápis", dica: "Instrumento para escrever ou desenhar" },
    { palavra: "cidade", dica: "Grande centro urbano" },
    { palavra: "caneta", dica: "Instrumento de escrita portátil" },
    { palavra: "amigo", dica: "Pessoa próxima e confiável" },
    { palavra: "terra", dica: "Planeta habitado onde vivemos" },
    { palavra: "planta", dica: "Organismo vivo que realiza fotossíntese" },
    { palavra: "mochila", dica: "Saco de tecido utilizado para transportar objetos" },
    { palavra: "fogão", dica: "Aparelho para cozinhar alimentos" },
    { palavra: "cama", dica: "Móvel para dormir" },
    { palavra: "rádio", dica: "Dispositivo para ouvir transmissões de áudio" },
    { palavra: "nuvem", dica: "Massa visível de gotículas de água ou cristais de gelo no céu" },
    { palavra: "garfo", dica: "Utensílio de mesa com dentes" },
    { palavra: "peixe", dica: "Animal aquático com nadadeiras" },
    { palavra: "espelho", dica: "Superfície que reflete imagens" },
    { palavra: "cachoeira", dica: "Queda d'água natural" },
    { palavra: "jardim", dica: "Área cultivada com plantas ornamentais" },
    { palavra: "ônibus", dica: "Veículo de transporte coletivo" },
    { palavra: "escada", dica: "Conjunto de degraus para subir ou descer" },
    { palavra: "televisão", dica: "Dispositivo para exibição de imagens e som" },
    { palavra: "teclado", dica: "Dispositivo de entrada para computadores" }
  ];
  